routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();


Route::group(['middleware' => 'is_worker'], function()
{
	// Route::get('/', 'HomeController@index')->name('/');
	Route::get('/home', 'HomeController@index')->name('home');
	Route::post('jobSearch', 'HomeController@jobSearch')->name('worker.jobSearch');
	Route::get('joblist', 'HomeController@jobList')->name('worker.jobList');
});

Route::group(['middleware' => 'is_job'], function()
{
	Route::resource('/job', 'JobController');
	Route::post('workerSearch', 'JobController@workerSearch')->name('job.workerSearch');
	Route::get('workerlist', 'JobController@workerList')->name('job.workerlist');
	Route::get('payment', 'JobController@payment')->name('job.payment');
});

app/Job.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Job extends Model
{
    // $fillable = [];

    public function user()
    {
        return $this->belongsTo('App\User');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'usertype'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function job()
    {
        return $this->hasOne('App\Job');
    }
}

app/helper.php
<?php

function calculate_time_span($days)
{ 
    $seconds = $days * 86400;
    $year = floor($seconds /31556926);
    $months = floor($seconds /2629743);
    $week=floor($seconds /604800);
    $day = floor($seconds /86400); 
    $hours = floor($seconds / 3600);
    $mins = floor(($seconds - ($hours*3600)) / 60); 
    $secs = floor($seconds % 60);
    if($seconds < 60) $time = $secs." seconds ago";
    else if($seconds < 3600 ) $time =($mins==1)?$mins."now":$mins." mins ago";
    else if($seconds < 86400) $time = ($hours==1)?$hours." hour ago":$hours." hours ago";
    else if($seconds < 604800) $time = ($day==1)?$day." day ago":$day." days ago";
    else if($seconds < 2629743) $time = ($week==1)?$week." week ago":$week." weeks ago";
    else if($seconds < 31556926) $time =($months==1)? $months." month ago":$months." months ago";
    else $time = ($year==1)? $year." year ago":$year." years ago";
    return $time; 
}

?>

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;
use Validator;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;

    public function ValidateForm($fields, $rules){
    	$validator = Validator::make($fields, $rules)->validate();
    }

}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Job;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('worker.home');
    }

    public function jobList()
    {
        return view('worker.joblist');
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function jobSearch(Request $request)
    {
        $jobs = Job::with('user');

        if ($request->searchText != '') {
            $jobs->where('title', 'LIKE', '%' . $request->searchText . '%');
        }

        if ($request->jobtype != '') {
            $jobs->whereIn('jobtype', $request->jobtype);
        }

        $jobs = $jobs->get();
        
        return view('worker.job_list')->with(['jobs' => $jobs]);
    }
}

app/Http/Controllers/JobController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Job;
use App\User;

class JobController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // $jobs = Job::where('user_id', Auth::guard()->user()->id)->get();
        // $workers = User::where('usertype', 'worker')->get();
        // return view('job.home')->with(['jobs' => $jobs, 'workers' => $workers]);
        return view('job.home');
    }

    public function workerList()
    {
        return view('job.workerlist');
    }

    public function payment()
    {
        return view('job.payment');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function workerSearch(Request $request)
    {
        $workers = User::where('usertype', 'worker');

        if ($request->text != '') {
            $workers->where('name', 'LIKE', '%' . $request->text . '%');
        }

        $workers = $workers->get();
        
        return view('job.worker_list')->with(['workers' => $workers]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('job.add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rules = [
            'title' => 'required',
            'description' => 'required',
            'technology' => 'required',
            'jobtype' => 'required',
            'budget' => 'required',
            'duration' => 'required',
        ];

        $this->validateForm($request->all(), $rules);

        $job = new Job();
        $job->user_id = Auth::guard()->user()->id;
        $job->title = $request->title;
        $job->description = $request->description;
        $job->technology = $request->technology;
        $job->jobtype = $request->jobtype;
        $job->budget = $request->budget;
        $job->duration = $request->duration;
        $job->save();

        // flash('Job added successfully.')->success();
        $request->session()->flash('status', 'Job was created successfully.');
        return redirect()->route('job.index');


    }

    
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        // return view('job.home');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/job/home.blade.php
@extends('layouts.app')

@section('content')
<div class="hero-wrap img" style="background-image: url(images/bg_1.jpg);">
      <div class="overlay"></div>
      <div class="container">
        <div class="row d-md-flex no-gutters slider-text align-items-center justify-content-center">
            <div class="col-md-10 d-flex align-items-center ftco-animate">
                <div class="text text-center pt-5 mt-md-5">
                    <p class="mb-4">Find Job, Employment, and Career Opportunities</p>
                <h1 class="mb-5">The Eassiest Way to Get Your New Job</h1>
                            <div class="ftco-counter ftco-no-pt ftco-no-pb">
                    </div>
                            <div class="ftco-search my-md-5">
                                <div class="row">
                        <div class="col-md-12 nav-link-wrap">
                            <div class="nav nav-pills text-center" id="v-pills-tab" role="tablist" aria-orientation="vertical">
                              <a class="nav-link active mr-md-1" id="v-pills-1-tab" href="{{ route('job.create') }}" role="tab" aria-controls="v-pills-1" aria-selected="true">Add Job</a>

                              <!-- <a class="nav-link" id="v-pills-2-tab" data-toggle="pill" href="#v-pills-2" role="tab" aria-controls="v-pills-2" aria-selected="false">Find a Candidate</a> -->

                            </div>
                          </div>
                        </div>
                    </div>
              </div>
            </div>
            </div>
      </div>
    </div>

<!-- <div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">{{ __('Home') }}</div>
                <div class="card-body">

                    {{ 'Welcome ' . Auth::guard()->user()->name }}
                    
                </div>
            </div>
        </div>
    </div>
</div> -->
@endsection

resources/views/job/worker_list.blade.php
@if(sizeof($workers) > 0)
    @foreach($workers as $worker)
        <div class="col-md-12">
            <div class="team d-md-flex p-4 bg-white">
            <div class="img" style="background-image: url(images/person_1.jpg);"></div>
            <div class="text pl-md-4">
                <!-- <span class="location mb-0">Western City, UK</span> -->
                <h2>{{ $worker->name }}</h2>
                <span class="position">{{ $worker->email }}</span>
                <!-- <p class="mb-2">Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p> -->
                <!-- <span class="seen">Last Activity 4 months ago</span> -->
                <p><a href="{{ route('job.payment') }}" class="btn btn-primary">Hire</a></p>
            </div>
        </div>
    </div>
        <!-- <div class="col-md-4 mb-3">
            <div class="card" style="width: 18rem;">
                <div class="card-body">
                    <h5 class="card-title">{{ $worker->name }}</h5>
                    <p class="card-text">{{ $worker->email }}</p>
                    <a href="{{ route('job.payment') }}"><button type="button" class="btn btn-success">Hire</button></a>
                </div>
            </div>
        </div> -->
    @endforeach
@else
<div class="col-md-4 mb-3">
    <div class="alert alert-danger text-center" role="alert">
        Not found.
    </div>
</div>
@endif

resources/views/job/workerlist.blade.php
@extends('layouts.app')

@section('content')
<div class="hero-wrap hero-wrap-2" style="background-image: url('images/bg_1.jpg');" data-stellar-background-ratio="0.5">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text align-items-end justify-content-start">
          <div class="col-md-12 ftco-animate text-center mb-5">
            <!-- <p class="breadcrumbs mb-0"><span class="mr-3"><a href="index.html">Home <i class="ion-ios-arrow-forward"></i></a></span> <span>About</span></p> -->
            <h1 class="mb-3 bread">Hire Your Best Candidates</h1>
          </div>
        </div>
      </div>
    </div>

    <section class="ftco-section ftco-candidates ftco-candidates-2 bg-light">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 pr-lg-4">
                    <div class="row workerList">
                    </div>
                </div>
                <div class="col-lg-4 sidebar">
                <div class="sidebar-box bg-white p-4 ftco-animate">
                    <h3 class="heading-sidebar">Browse Category</h3>
                    <form action="#" class="search-form mb-3">
                <div class="form-group">
                  <span class="icon icon-search"></span>
                  <input type="text" id="searchWorkerText" class="form-control" placeholder="Search...">
                </div>
              </form>
                </div>
              </div>
            </div>
        </div>
    </section>
<!-- <div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">{{ __('Job Listing') }}</div>
                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    @endif

                    <form class="form-inline mb-3">
                      <div class="form-group">
                        <label for="inputPassword6">Search: </label>
                        <input type="text" id="searchWorkerText" class="form-control mx-sm-3 searchWorkerText" placeholder="Search Worker">
                      </div>
                    </form>

                    <div class="row workerList">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div> -->
@endsection


@push('scripts')
<script type="text/javascript">
    $(document).ready(function() {
        searchWroker();
    });
    
    $(document).on('keyup', '#searchWorkerText', function(e) {
        var searchText = $(this).val();
        searchWroker(searchText);
    });

    function searchWroker(text = '') {
        $.ajax({
            type: "POST",
            url: "{{ route('job.workerSearch') }}",
            data: {'text': text, _token: '{!! csrf_token() !!}'},
            cache: false,
            success: function(data)
            {
                $('.workerList').html(data);
            } 
        });
    }
</script>
@endpush

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'JobSearch') }}</title>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <!-- <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet"> -->
    <!-- <link rel="stylesheet" href="{{ asset('css/font-awesome-4.7.0/css/font-awesome.min.css') }}"> -->
    <!-- Styles -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{{ asset('css/open-iconic-bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('css/animate.css') }}">
    
    <link rel="stylesheet" href="{{ asset('css/owl.carousel.min.css') }}">
    <link rel="stylesheet" href="{{ asset('css/owl.theme.default.min.css') }}">
    <link rel="stylesheet" href="{{ asset('css/magnific-popup.css') }}">

    <link rel="stylesheet" href="{{ asset('css/aos.css') }}">

    <link rel="stylesheet" href="{{ asset('css/ionicons.min.css') }}">

    <link rel="stylesheet" href="{{ asset('css/bootstrap-datepicker.css') }}">
    <link rel="stylesheet" href="{{ asset('css/jquery.timepicker.css') }}">

    
    <link rel="stylesheet" href="{{ asset('css/flaticon.css') }}">
    <link rel="stylesheet" href="{{ asset('css/icomoon.css') }}">
    <link rel="stylesheet" href="{{ asset('css/style.css') }}">

    <!-- <link href="{{ asset('css/app.css') }}" rel="stylesheet"> -->
    <link href="{{ asset('css/custom.css') }}" rel="stylesheet">
    <!-- Scripts -->
    <!-- <script src="{{ asset('js/app.js') }}" defer></script> -->
    
</head>
<body>
    <!-- <div id="app"> -->
        <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
        <div class="container-fluid px-md-4 ">
          <a class="navbar-brand" href="{{ url('/home') }}">{{ config('app.name', 'JobSearch') }}</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="oi oi-menu"></span> Menu
          </button>

          <div class="collapse navbar-collapse" id="ftco-nav">
            <ul class="navbar-nav ml-auto">
                @if (Auth::check())
                    @if (Auth::user()->usertype == 'worker')
                        <li class="nav-item {{ (request()->is('home')) ? 'active' : '' }}">
                            <a href="{{ url('/home') }}" class="nav-link">Home</a>
                        </li>
                        <li class="nav-item {{ (request()->is('joblist')) ? 'active' : '' }}">
                            <a href="{{ route('worker.jobList') }}" class="nav-link">Job</a>
                        </li>
                    @else
                        <li class="nav-item {{ (request()->is('job')) ? 'active' : '' }}">
                            <a href="{{ route('job.index') }}" class="nav-link">Home</a>
                        </li>
                        <li class="nav-item {{ (request()->is('workerlist')) ? 'active' : '' }}">
                            <a href="{{ route('job.workerlist') }}" class="nav-link">Workers</a>
                        </li>
                        <li class="nav-item {{ (request()->is('job/create')) ? 'active' : '' }}">
                            <a href="{{ route('job.create') }}" class="nav-link">Add Job</a>
                        </li>
                    @endif
                @endif

                @guest
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                    </li>
                    @if (Route::has('register'))
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                        </li>
                    @endif
                @else
                    <li class="nav-item dropdown">
                        <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                            {{ Auth::user()->name }} <span class="caret"></span>
                        </a>

                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{{ route('logout') }}"
                               onclick="event.preventDefault();
                                             document.getElementById('logout-form').submit();">
                                {{ __('Logout') }}
                            </a>

                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                @csrf
                            </form>
                        </div>
                    </li>
                @endguest
              
              <!-- <li class="nav-item"><a href="browsejobs.html" class="nav-link">Browse Jobs</a></li>
              <li class="nav-item"><a href="candidates.html" class="nav-link">Canditates</a></li>
              <li class="nav-item"><a href="blog.html" class="nav-link">Blog</a></li>
              <li class="nav-item"><a href="contact.html" class="nav-link">Contact</a></li>
              <li class="nav-item cta mr-md-1"><a href="new-post.html" class="nav-link">Post a Job</a></li>
              <li class="nav-item cta cta-colored"><a href="job-post.html" class="nav-link">Want a Job</a></li> -->

            </ul>
          </div>
        </div>
      </nav>

        <!-- <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'JobSearch') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    
                    <div class="collapse navbar-collapse" id="navbarNavDropdown">
                        <ul class="navbar-nav">
                            @if (Auth::check())
                                @if (Auth::user()->usertype == 'worker')
                                    <li class="nav-item {{ (request()->is('home')) ? 'active' : '' }}">
                                        <a class="nav-link" href="{{ route('home') }}">Home <span class="sr-only">(current)</span></a>
                                    </li>
                                    <li class="nav-item {{ (request()->is('joblist')) ? 'active' : '' }}">
                                        <a class="nav-link" href="{{ route('worker.jobList') }}">Jobs</a>
                                    </li>
                                @else
                                    <li class="nav-item {{ (request()->is('job')) ? 'active' : '' }}">
                                        <a class="nav-link" href="{{ route('job.index') }}">Home <span class="sr-only">(current)</span></a>
                                    </li>
                                    <li class="nav-item dropdown {{ (request()->is('workerlist') || request()->is('job/create')) ? 'active' : '' }}">
                                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Workers
                                        </a>
                                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                          <a class="dropdown-item" href="{{ route('job.workerlist') }}">Workes List</a>
                                          <a class="dropdown-item" href="{{ route('job.create') }}">Add Job</a>
                                        </div>
                                    </li>
                                @endif
                            @endif
                        </ul>
                    </div>

                   
                    <ul class="navbar-nav ml-auto">
                      
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav> -->

        <!-- <main class="py-4"> -->
            @yield('content')
        <!-- </main> -->
    <!-- </div> -->
</body>
<!-- <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script> -->
<script src="{{ asset('js/jquery.min.js') }}"></script>
<script src="{{ asset('js/jquery-migrate-3.0.1.min.js') }}"></script>
<script src="{{ asset('js/popper.min.js') }}"></script>
<script src="{{ asset('js/bootstrap.min.js') }}"></script>
<script src="{{ asset('js/jquery.easing.1.3.js') }}"></script>
<script src="{{ asset('js/jquery.waypoints.min.js') }}"></script>
<script src="{{ asset('js/jquery.stellar.min.js') }}"></script>
<script src="{{ asset('js/owl.carousel.min.js') }}"></script>
<script src="{{ asset('js/jquery.magnific-popup.min.js') }}"></script>
<script src="{{ asset('js/aos.js') }}"></script>
<script src="{{ asset('js/jquery.animateNumber.min.js') }}"></script>
<script src="{{ asset('js/scrollax.min.js') }}"></script>
<script src="{{ asset('js/main.js') }}"></script>
@stack('scripts')
</html>

resources/views/worker/home.blade.php
@extends('layouts.app')

@section('content')
<!-- <div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">{{ __('Home') }}</div>

                <div class="card-body">

                    {{ 'Hello ' . Auth::guard()->user()->name }}
            
                </div>
            </div>
        </div>
    </div>
</div> -->

<div class="hero-wrap img" style="background-image: url(images/bg_1.jpg);">
      <div class="overlay"></div>
      <div class="container">
        <div class="row d-md-flex no-gutters slider-text align-items-center justify-content-center">
            <div class="col-md-10 d-flex align-items-center ftco-animate">
                <div class="text text-center pt-5 mt-md-5">
                    <p class="mb-4">Find Job, Employment, and Career Opportunities</p>
                <h1 class="mb-5">The Eassiest Way to Get Your New Job</h1>
                            <div class="ftco-counter ftco-no-pt ftco-no-pb">
                    </div>
                            <div class="ftco-search my-md-5">
                                <div class="row">
                        <div class="col-md-12 nav-link-wrap">
                            <div class="nav nav-pills text-center" id="v-pills-tab" role="tablist" aria-orientation="vertical">
                              <a class="nav-link active mr-md-1" id="v-pills-1-tab" href="{{ route('worker.jobList') }}" role="tab" aria-controls="v-pills-1" aria-selected="true">Find a Job</a>

                              <!-- <a class="nav-link" id="v-pills-2-tab" data-toggle="pill" href="#v-pills-2" role="tab" aria-controls="v-pills-2" aria-selected="false">Find a Candidate</a> -->

                            </div>
                          </div>
                        </div>
                    </div>
              </div>
            </div>
            </div>
      </div>
    </div>
@endsection

resources/views/worker/job_list.blade.php
@if(sizeof($jobs) > 0)
    @foreach($jobs as $job)
        <div class="col-md-12">
            <div class="job-post-item p-4 d-block d-lg-flex align-items-center">
              <div class="one-third mb-4 mb-md-0">
                <div class="job-post-item-header align-items-center">
                    <span class="subadge">{{ $job->jobtype }}</span>
                  <h2 class="mr-3 text-black"><a href="javascript:void(0);">{{ $job->title }}</a></h2>
                  <p>{{ $job->description }}</p>
                </div>
                <div class="job-post-item-body d-block d-md-flex">
                  <div class="mr-3"><span class="icon-layers"></span>{{ $job->user->name }}</div>
                  <div><span class="icon-desktop"></span> <span>{{ $job->technology }}</span></div>
                </div>
              </div>

              <div class="one-forth ml-auto d-flex align-items-center mt-4 md-md-0">
                <a href="job-single.html" class="btn btn-primary py-2">Apply Job</a>
              </div>
            </div>
          </div>
    @endforeach
@else
<div class="col-md-4 mb-3">
    <div class="alert alert-danger text-center" role="alert">
        Not found.
    </div>
</div>
@endif